In [2]:
import numpy as np
from pyDatalog import pyDatalog
from pyDatalog import pyEngine

def maxOfProduct(x, y):
    z = []
    for x1 in x:
        for y1 in y.T:
            z.append(max(np.multiply(x1, y1)))
    return np.array(z).reshape((x.shape[0], y.shape[1]))

r1 = np.array([[0, 0.2, 0.7, 0.8], [0, 0.3, 0.7, 0.5], [0.5, 0.5, 0.5, 0.5], [0.7, 0.4, 0.4, 0.6], [0.7, 0.7, 0.3, 0.3]])
r2 = np.array([[0, 0.3, 0.3, 0.7, 0], [0.3, 0.1, 0.7, 0.3, 0.8], [0.8, 0.6, 0.5, 0.4, 0.3], [0.8, 0.8, 0.5, 0.6, 0.2]])

print("Армия колдунов: \n")
print("Скелеты: ", r1[0])
print("Зомби: ", r1[1])
print("Вампиры: ", r1[2])
print("Ведьмы: ", r1[3])
print("Костяной дракон: ", r1[4], "\n")

print("Армия волшебников: \n")
print("Эф. Магия: ", r2[0])
print("Эф. Физ. Атак: ", r2[1])
print("Вос. Магия: ", r2[2])
print("Вос. Физ. Атак: ", r2[3], "\n")

print("Эффективность способностей(столбцы - волшебники, строки - колдуны): \n")
print(maxOfProduct(r1, r2))

Армия колдунов: 

Скелеты:  [ 0.   0.2  0.7  0.8]
Зомби:  [ 0.   0.3  0.7  0.5]
Вампиры:  [ 0.5  0.5  0.5  0.5]
Ведьмы:  [ 0.7  0.4  0.4  0.6]
Костяной дракон:  [ 0.7  0.7  0.3  0.3] 

Армия волшебников: 

Эф. Магия:  [ 0.   0.3  0.3  0.7  0. ]
Эф. Физ. Атак:  [ 0.3  0.1  0.7  0.3  0.8]
Вос. Магия:  [ 0.8  0.6  0.5  0.4  0.3]
Вос. Физ. Атак:  [ 0.8  0.8  0.5  0.6  0.2] 

Эффективность способностей(столбцы - волшебники, строки - колдуны): 

[[ 0.64  0.64  0.4   0.48  0.21]
 [ 0.56  0.42  0.35  0.3   0.24]
 [ 0.4   0.4   0.35  0.35  0.4 ]
 [ 0.48  0.48  0.3   0.49  0.32]
 [ 0.24  0.24  0.49  0.49  0.56]]


Моя армия волшебников:
Титан(кол-во: 1) против Костяного дракона
Феи(кол-во: 2) против Ведьм
Рыцари(кол-во: 3) против Вампиров
Крестьяне(кол-во: 5) против Зомби
Эльфы(кол-во: 8) против Скелетов

Итоговая сумма: 2610 золотых